export const BRAND_ASSETS = {
  version: "2026.2-wardrobe",
  logo: {
    svg: "/brand/logo.svg",
    png: "/logo.png",
    share: "/logo",
    runtimeSvg: "/brand/logo.svg?v=2026.2-wardrobe",
  },
  wordmark: {
    svg: "/brand/wordmark.svg",
    reverseSvg: "/brand/wordmark-white.svg",
    png: "/wordmark.png",
    share: "/wordmark",
    runtimeSvg: "/brand/wordmark.svg?v=2026.2-wardrobe",
    runtimeReverseSvg: "/brand/wordmark-white.svg?v=2026.2-wardrobe",
  },
  icon: {
    svg: "/brand/icon.svg",
    png: "/icon.png",
    share: "/icon",
    runtimeSvg: "/brand/icon.svg?v=2026.2-wardrobe",
    app192: "/brand/icon-192.png",
    app512: "/brand/icon-512.png",
    maskable512: "/brand/icon-maskable-512.png",
    appleTouch: "/brand/apple-touch-icon.png",
    runtimeApp192: "/brand/icon-192.png?v=2026.2-wardrobe",
    runtimeApp512: "/brand/icon-512.png?v=2026.2-wardrobe",
    runtimeMaskable512: "/brand/icon-maskable-512.png?v=2026.2-wardrobe",
    runtimeAppleTouch: "/brand/apple-touch-icon.png?v=2026.2-wardrobe",
  },
  favicon: {
    svg: "/favicon.svg",
    ico: "/favicon.ico",
    runtimeSvg: "/favicon.svg?v=2026.2-wardrobe",
    runtimeIco: "/favicon.ico?v=2026.2-wardrobe",
  },
} as const;
