export const BRAND_ASSETS = {
  version: "2026.3-seal",
  logo: {
    svg: "/brand/logo.svg",
    png: "/logo.png",
    share: "/logo",
    runtimeSvg: "/brand/logo.svg?v=2026.2-wardrobe",
  },
  wordmark: {
    svg: "/brand/wordmark.svg",
    reverseSvg: "/brand/wordmark-white.svg",
    png: "/wordmark.png",
    share: "/wordmark",
    runtimeSvg: "/brand/wordmark.svg?v=2026.2-wardrobe",
    runtimeReverseSvg: "/brand/wordmark-white.svg?v=2026.2-wardrobe",
  },
  icon: {
    svg: "/brand/icon.svg",
    png: "/icon.png",
    share: "/icon",
    runtimeSvg: "/brand/icon.svg?v=2026.3-seal",
    app192: "/brand/icon-192.png",
    app512: "/brand/icon-512.png",
    maskable512: "/brand/icon-maskable-512.png",
    appleTouch: "/brand/apple-touch-icon.png",
    runtimeApp192: "/brand/icon-192.png?v=2026.3-seal",
    runtimeApp512: "/brand/icon-512.png?v=2026.3-seal",
    runtimeMaskable512: "/brand/icon-maskable-512.png?v=2026.3-seal",
    runtimeAppleTouch: "/brand/apple-touch-icon.png?v=2026.3-seal",
    motionMaster: "/brand/icon-master-1024.png?v=2026.3-seal",
    motionManifest: "/brand/motion/manifest.json?v=2026.3-seal",
  },
  favicon: {
    svg: "/favicon.svg",
    ico: "/favicon.ico",
    runtimeSvg: "/favicon.svg?v=2026.3-seal",
    runtimeIco: "/favicon.ico?v=2026.3-seal",
  },
  social: {
    profile: "/brand/social-profile.png",
    og: "/brand/social-og.png",
    runtimeProfile: "/brand/social-profile.png?v=2026.2-role-corrected",
    runtimeOg: "/brand/social-og.png?v=2026.2-owner-signage",
  },
} as const;
