import type { WardrobePublicProduct } from "./domain/entities";

export type WardrobeDrop01Product = Omit<WardrobePublicProduct, "media" | "modelAnchor">;

/**
 * The six real-worn dresses are saleable wardrobe rows, not a parallel preview
 * catalogue. Exact tagged size and measurements are confirmed before payment.
 */
export const WARDROBE_DROP_01_PRODUCTS = [
  {
    slug: "blush-scoop-mini-dress",
    sku: "DYN-087",
    name: "Blush Scoop Mini Dress",
    category: "Dresses",
    price: 18500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Blush pink",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "salmon",
    silhouette: "dress",
    note: "A close blush mini with a clean scoop neckline and soft gathered shape.",
    story: "The simplest dress in the drop: warm blush, an open neckline, and a fitted line that stays easy rather than overworked.",
    details: ["Scoop neckline", "Fitted mini length", "Soft stretch hand", "Real-worn wardrobe piece"],
    measurements: [],
  },
  {
    slug: "orchid-beaded-column-gown",
    sku: "DYN-088",
    name: "Orchid Beaded Column Gown",
    category: "Dresses",
    price: 32000,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Orchid / mauve",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "cocoa",
    silhouette: "dress",
    note: "A floor-length orchid column with tonal beadwork and a held, evening line.",
    story: "Orchid and mauve move through the beadwork without breaking the long silhouette. It is the occasion piece in Drop 01.",
    details: ["Tonal beadwork", "Halter neckline", "Column silhouette", "Floor length"],
    measurements: [],
  },
  {
    slug: "sage-asymmetric-ruched-maxi-dress",
    sku: "DYN-089",
    name: "Sage Asymmetric Ruched Maxi Dress",
    category: "Dresses",
    price: 28500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Soft sage",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "moss",
    silhouette: "dress",
    note: "Soft sage draped into an asymmetric neckline and a long ruched fall.",
    story: "The colour is quiet; the construction is not. An asymmetric top and gathered body make this maxi read differently from every angle.",
    details: ["Asymmetric neckline", "Ruched drape", "Maxi length", "Soft sage finish"],
    measurements: [],
  },
  {
    slug: "magenta-plunge-ruched-mini-dress",
    sku: "DYN-090",
    name: "Magenta Plunge Ruched Mini Dress",
    category: "Dresses",
    price: 22000,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Vivid magenta",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "coral",
    silhouette: "dress",
    note: "A vivid plunge mini with controlled ruching and a sharp evening energy.",
    story: "Magenta carries the impact while the gathered construction holds the silhouette close. Built for a direct, uncomplicated night look.",
    details: ["Plunge neckline", "Ruched body", "Mini length", "Vivid magenta finish"],
    measurements: [],
  },
  {
    slug: "silver-off-shoulder-mermaid-dress",
    sku: "DYN-091",
    name: "Silver Off-Shoulder Mermaid Dress",
    category: "Dresses",
    price: 34500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Silver grey",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "ivory",
    silhouette: "dress",
    note: "A sculpted silver evening dress with an off-shoulder line and mermaid finish.",
    story: "A cool silver surface, exposed shoulder line, and shaped hem give this dress the most formal stance in the wardrobe release.",
    details: ["Off-shoulder neckline", "Sculpted bodice", "Mermaid silhouette", "Silver finish"],
    measurements: [],
  },
  {
    slug: "multicolor-abstract-strapless-mini-dress",
    sku: "DYN-092",
    name: "Multicolor Abstract Strapless Mini Dress",
    category: "Dresses",
    price: 19500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Multicolor abstract print",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "salmon",
    silhouette: "dress",
    note: "A strapless fitted mini cut through with a vivid abstract print.",
    story: "Black, burgundy, cobalt, lime, and blush move through a compact silhouette. The print does the talking; the shape stays clean.",
    details: ["Strapless neckline", "Fitted mini length", "Gathered hip", "Abstract multicolor print"],
    measurements: [],
  },
] as const satisfies readonly WardrobeDrop01Product[];

/** Only identity-gated frames that actually exist may cross into Shop. */
export const WARDROBE_DROP_01_APPROVED_MODEL_FRONT_SLUGS = Object.freeze([
  "blush-scoop-mini-dress",
  "orchid-beaded-column-gown",
  "multicolor-abstract-strapless-mini-dress",
] as const);
