import type { WardrobePublicProduct } from "./domain/entities";

export type WardrobeDrop01Product = Omit<WardrobePublicProduct, "media" | "modelAnchor">;

/**
 * The real-worn pieces are saleable wardrobe rows, not a parallel preview
 * catalogue. Exact tagged size and measurements are confirmed before payment.
 */
export const WARDROBE_DROP_01_PRODUCTS = [
  {
    slug: "blush-scoop-mini-dress",
    sku: "JUW-007",
    name: "Blush Scoop Mini Dress",
    category: "Dresses",
    price: 18500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Blush pink",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "salmon",
    silhouette: "dress",
    note: "A close blush mini with a clean scoop neckline and soft gathered shape.",
    story: "The simplest dress in the drop: warm blush, an open neckline, and a fitted line that stays easy rather than overworked.",
    details: ["Scoop neckline", "Fitted mini length", "Soft stretch hand", "Real-worn wardrobe piece"],
    measurements: [],
  },
  {
    slug: "orchid-beaded-column-gown",
    sku: "JUW-008",
    name: "Orchid Beaded Column Gown",
    category: "Dresses",
    price: 32000,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Orchid / mauve",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "cocoa",
    silhouette: "dress",
    note: "A floor-length orchid column with tonal beadwork and a held, evening line.",
    story: "Orchid and mauve move through the beadwork without breaking the long silhouette. It is the occasion piece in Drop 01.",
    details: ["Tonal beadwork", "Halter neckline", "Column silhouette", "Floor length"],
    measurements: [],
  },
  {
    slug: "sage-asymmetric-ruched-maxi-dress",
    sku: "JUW-009",
    name: "Sage Asymmetric Ruched Maxi Dress",
    category: "Dresses",
    price: 28500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Soft sage",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "moss",
    silhouette: "dress",
    note: "Soft sage draped into an asymmetric neckline and a long ruched fall.",
    story: "The colour is quiet; the construction is not. An asymmetric top and gathered body make this maxi read differently from every angle.",
    details: ["Asymmetric neckline", "Ruched drape", "Maxi length", "Soft sage finish"],
    measurements: [],
  },
  {
    slug: "magenta-plunge-ruched-mini-dress",
    sku: "JUW-010",
    name: "Magenta Plunge Ruched Mini Dress",
    category: "Dresses",
    price: 22000,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Vivid magenta",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "coral",
    silhouette: "dress",
    note: "A vivid plunge mini with controlled ruching and a sharp evening energy.",
    story: "Magenta carries the impact while the gathered construction holds the silhouette close. Built for a direct, uncomplicated night look.",
    details: ["Plunge neckline", "Ruched body", "Mini length", "Vivid magenta finish"],
    measurements: [],
  },
  {
    slug: "silver-off-shoulder-mermaid-dress",
    sku: "JUW-011",
    name: "Silver Off-Shoulder Mermaid Dress",
    category: "Dresses",
    price: 34500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Silver grey",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "ivory",
    silhouette: "dress",
    note: "A sculpted silver evening dress with an off-shoulder line and mermaid finish.",
    story: "A cool silver surface, exposed shoulder line, and shaped hem give this dress the most formal stance in the wardrobe release.",
    details: ["Off-shoulder neckline", "Sculpted bodice", "Mermaid silhouette", "Silver finish"],
    measurements: [],
  },
  {
    slug: "multicolor-abstract-strapless-mini-dress",
    sku: "JUW-012",
    name: "Multicolor Abstract Strapless Mini Dress",
    category: "Dresses",
    price: 19500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Multicolor abstract print",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "salmon",
    silhouette: "dress",
    note: "A strapless fitted mini cut through with a vivid abstract print.",
    story: "Black, burgundy, cobalt, lime, and blush move through a compact silhouette. The print does the talking; the shape stays clean.",
    details: ["Strapless neckline", "Fitted mini length", "Gathered hip", "Abstract multicolor print"],
    measurements: [],
  },
  {
    slug: "teal-draped-mini-set",
    sku: "JUW-013",
    name: "Teal Draped Mini Set",
    category: "Sets",
    price: 24500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Teal",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "indigo",
    silhouette: "set",
    note: "A teal two-piece set.",
    story: "A draped top paired with a close mini skirt.",
    details: ["Two-piece set"],
    measurements: [],
  },
  {
    slug: "sage-open-back-high-slit-maxi-dress",
    sku: "JUW-014",
    name: "Sage Open-Back High-Slit Maxi Dress",
    category: "Dresses",
    price: 28500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Soft sage",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "moss",
    silhouette: "dress",
    note: "A sage long-sleeve maxi shaped with side ruching, a tied open back, and a high slit.",
    story: "The restrained sage colour holds a dramatic back: an oval opening secured with ties, balanced by a fitted ruched line and high side slit.",
    details: ["Round neckline", "Tied oval open back", "Side ruching", "High side slit"],
    measurements: [],
  },
  {
    slug: "cocoa-cowl-gathered-midi-dress",
    sku: "JUW-015",
    name: "Cocoa Cowl Gathered Midi Dress",
    category: "Dresses",
    price: 24500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Cocoa taupe",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "cocoa",
    silhouette: "dress",
    note: "A cocoa-taupe midi dress with a softly draped cowl front and gathered waist.",
    story: "A quiet cocoa stretch line softened by a draped neckline and subtle right-waist gathering.",
    details: ["Softly draped cowl neckline", "Subtle right-waist gathering", "Close long silhouette", "Smooth stretch jersey"],
    measurements: [],
  },
  {
    slug: "ivory-rib-knit-fitted-midi-dress",
    sku: "JUW-016",
    name: "Ivory Rib-Knit Fitted Midi Dress",
    category: "Dresses",
    price: 24500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Warm ivory",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "ivory",
    silhouette: "dress",
    note: "A warm-ivory rib-knit midi drawn close with adjustable side ruching.",
    story: "Fine vertical ribbing keeps the fitted line clean, while the wearer-left drawstring gathers the side without interrupting the plain back.",
    details: ["Fine vertical rib knit", "Shallow wide neckline", "Cap sleeves", "Adjustable side ruching"],
    measurements: [],
  },
  {
    slug: "coral-gathered-crop-mini-set",
    sku: "JUW-020",
    name: "Coral Gathered Crop-Top and Mini-Skirt Set",
    category: "Sets",
    price: 24500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Vivid coral",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "coral",
    silhouette: "set",
    note: "A coral two-piece pairing a gathered crop top with a close mini skirt.",
    story: "A softly gathered bust and slim straps balance the clean high-waisted mini skirt for one compact coral line.",
    details: ["Gathered crop top", "Slim shoulder straps", "High-waisted mini skirt", "Smooth stretch finish"],
    measurements: [],
  },
  {
    slug: "cropped-denim-jacket-black-legging-look",
    sku: "JUW-021",
    name: "Cropped Denim Jacket and Black Legging Look",
    category: "Sets",
    price: 24500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Excellent · real-worn wardrobe piece",
    colour: "Washed blue and black",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "indigo",
    silhouette: "set",
    note: "A cropped washed-denim jacket paired with full-length black leggings.",
    story: "Light washed denim and clean black stretch make an easy two-piece line, finished with buttoned flap pockets and a sharply cropped jacket hem.",
    details: ["Cropped denim jacket", "Buttoned flap chest pockets", "Long sleeves with button cuffs", "Full-length black leggings"],
    measurements: [],
  },
] as const satisfies readonly WardrobeDrop01Product[];

/** Only identity-gated frames that actually exist may cross into Shop. */
export const WARDROBE_DROP_01_APPROVED_MODEL_FRONT_SLUGS = Object.freeze([
  "blush-scoop-mini-dress",
  "orchid-beaded-column-gown",
  "multicolor-abstract-strapless-mini-dress",
  "teal-draped-mini-set",
  "sage-open-back-high-slit-maxi-dress",
] as const);
