import type {
  WardrobePublicMedia,
  WardrobePublicMediaSlot,
  WardrobePublicModelAnchor,
  WardrobePublicModelAnchorId,
  WardrobePublicProduct,
  WardrobePublicViewSnapshot,
} from "./domain/entities";
import {
  WARDROBE_DROP_01_APPROVED_MODEL_FRONT_SLUGS,
  WARDROBE_DROP_01_PRODUCTS,
} from "./drop-01";

export const WARDROBE_PUBLIC_MODEL_ANCHORS = Object.freeze({
  "lulu-v2": Object.freeze({
    id: "lulu-v2" as const,
    src: "/shop/model/lulu-v2-approved.png" as const,
  }),
  "lulu-v3": Object.freeze({ id: "lulu-v3" as const }),
  "lulu-v4": Object.freeze({ id: "lulu-v4" as const }),
});

/** The public V2 identity reference remains the default and is never replaced by a private master. */
export const WARDROBE_PUBLIC_MODEL_ANCHOR = WARDROBE_PUBLIC_MODEL_ANCHORS["lulu-v2"];

export const WARDROBE_APPROVED_V3_MODEL_FRONT_SLUGS = Object.freeze([
  "coral-drift-dress",
  "indigo-workshirt",
  "moss-square-knit",
  "cocoa-pleat-trouser",
  "salmon-camp-shirt",
  "teal-draped-mini-set",
  "sage-open-back-high-slit-maxi-dress",
] as const);

export const WARDROBE_APPROVED_V4_MODEL_SLUGS = Object.freeze([
  "black-cropped-tee-slim-trouser-set",
  "violet-beaded-ruffle-romper",
  "black-sweetheart-fit-flare-midi-dress",
  "black-ivory-folded-neck-column-dress",
  "indigo-seamed-denim-mini-dress",
  "black-cropped-tee-silver-ruched-skirt-set",
  "black-cropped-tee-pink-distressed-shorts-set",
  "black-cropped-tee-blue-distressed-shorts-set",
  "black-cropped-tee-charcoal-cutoff-shorts-set",
  "black-cropped-tee-mid-thigh-black-cutoff-shorts-set",
  "black-cropped-tee-light-wash-snap-panel-trousers-set",
  "black-cropped-tee-blue-wash-drawstring-barrel-trousers-set",
  "black-cropped-tee-charcoal-wash-wide-leg-cargo-jeans-set",
  "black-cropped-tee-dark-indigo-wide-leg-cargo-jeans-set",
  "black-cropped-tee-washed-black-wide-leg-cargo-jeans-set",
  "plum-sparkle-cowl-neck-jumpsuit",
  "fuchsia-strapless-ruched-cascade-ruffle-mini-dress",
  "charcoal-wrap-front-ruched-slit-midi-dress",
  "marigold-sculptural-rosette-strapless-mini-dress",
  "scarlet-rosette-halter-cutout-ruched-mini-dress",
  "crimson-asymmetric-draped-satin-maxi-dress",
  "scarlet-asymmetric-cascade-ruched-mini-dress",
  "black-asymmetric-sculpted-shoulder-mini-dress",
] as const);

export const WARDROBE_APPROVED_MODEL_FRONT_SLUGS = Object.freeze([
  "coral-drift-dress",
  "indigo-workshirt",
  "moss-square-knit",
  "ivory-tie-skirt",
  "cocoa-pleat-trouser",
  "salmon-camp-shirt",
  ...WARDROBE_DROP_01_APPROVED_MODEL_FRONT_SLUGS,
  ...WARDROBE_APPROVED_V4_MODEL_SLUGS,
] as const);

type WardrobeSupplementalModelSlot = Extract<
  WardrobePublicMediaSlot,
  "MODEL_LEFT_PROFILE" | "MODEL_REAR_THREE_QUARTER" | "MODEL_REAR_MIRROR" | "MODEL_DETAIL"
>;

export const WARDROBE_APPROVED_MODEL_SUPPLEMENTAL_SLOTS = Object.freeze({
  "black-cropped-tee-slim-trouser-set": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "violet-beaded-ruffle-romper": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-sweetheart-fit-flare-midi-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-ivory-folded-neck-column-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "indigo-seamed-denim-mini-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-cropped-tee-silver-ruched-skirt-set": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-cropped-tee-pink-distressed-shorts-set": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-cropped-tee-blue-distressed-shorts-set": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-cropped-tee-charcoal-cutoff-shorts-set": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-cropped-tee-mid-thigh-black-cutoff-shorts-set": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-cropped-tee-light-wash-snap-panel-trousers-set": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-cropped-tee-blue-wash-drawstring-barrel-trousers-set": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-cropped-tee-charcoal-wash-wide-leg-cargo-jeans-set": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-cropped-tee-dark-indigo-wide-leg-cargo-jeans-set": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-cropped-tee-washed-black-wide-leg-cargo-jeans-set": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "plum-sparkle-cowl-neck-jumpsuit": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "fuchsia-strapless-ruched-cascade-ruffle-mini-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "charcoal-wrap-front-ruched-slit-midi-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "marigold-sculptural-rosette-strapless-mini-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "scarlet-rosette-halter-cutout-ruched-mini-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "crimson-asymmetric-draped-satin-maxi-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "scarlet-asymmetric-cascade-ruched-mini-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "black-asymmetric-sculpted-shoulder-mini-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "coral-drift-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "moss-square-knit": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "cocoa-pleat-trouser": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "magenta-plunge-ruched-mini-dress": [
    "MODEL_LEFT_PROFILE",
    "MODEL_REAR_THREE_QUARTER",
    "MODEL_DETAIL",
  ],
  "silver-off-shoulder-mermaid-dress": ["MODEL_REAR_THREE_QUARTER"],
  "orchid-beaded-column-gown": ["MODEL_DETAIL"],
  "sage-open-back-high-slit-maxi-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "cocoa-cowl-gathered-midi-dress": ["MODEL_LEFT_PROFILE", "MODEL_REAR_THREE_QUARTER"],
  "ivory-rib-knit-fitted-midi-dress": ["MODEL_LEFT_PROFILE"],
  "teal-draped-mini-set": ["MODEL_REAR_MIRROR"],
  "coral-gathered-crop-mini-set": ["MODEL_REAR_THREE_QUARTER"],
  "cropped-denim-jacket-black-legging-look": ["MODEL_REAR_MIRROR"],
} as const satisfies Record<string, readonly WardrobeSupplementalModelSlot[]>);

export function getApprovedModelSupplementalSlots(
  slug: string,
): readonly WardrobeSupplementalModelSlot[] {
  return Object.hasOwn(WARDROBE_APPROVED_MODEL_SUPPLEMENTAL_SLOTS, slug)
    ? WARDROBE_APPROVED_MODEL_SUPPLEMENTAL_SLOTS[
        slug as keyof typeof WARDROBE_APPROVED_MODEL_SUPPLEMENTAL_SLOTS
      ]
    : [];
}

const modelFrontSlugs = new Set<string>(WARDROBE_APPROVED_MODEL_FRONT_SLUGS);
const v3ModelFrontSlugs = new Set<string>(WARDROBE_APPROVED_V3_MODEL_FRONT_SLUGS);
const v4ModelSlugs = new Set<string>(WARDROBE_APPROVED_V4_MODEL_SLUGS);
const v3SupplementalModelSlugs = new Set([
  "teal-draped-mini-set",
  "sage-open-back-high-slit-maxi-dress",
  "cocoa-cowl-gathered-midi-dress",
  "ivory-rib-knit-fitted-midi-dress",
  "coral-gathered-crop-mini-set",
  "cropped-denim-jacket-black-legging-look",
]);
const constructionDetailSlugs = new Set([
  "sage-open-back-high-slit-maxi-dress",
  "coral-gathered-crop-mini-set",
]);

const modelMediaSlots = new Set<WardrobePublicMediaSlot>([
  "MODEL_FRONT",
  "MODEL_LEFT_PROFILE",
  "MODEL_REAR_THREE_QUARTER",
  "MODEL_REAR_MIRROR",
  "MODEL_DETAIL",
]);

const supplementalModelFiles: Record<WardrobeSupplementalModelSlot, string> = {
  MODEL_LEFT_PROFILE: "07-model-left-profile.webp",
  MODEL_REAR_THREE_QUARTER: "05-model-rear-three-quarter.webp",
  MODEL_REAR_MIRROR: "09-model-rear-mirror.webp",
  MODEL_DETAIL: "08-model-detail.webp",
};

export function getApprovedModelAnchorId(
  slug: string,
  slot: WardrobePublicMediaSlot,
): WardrobePublicModelAnchorId | undefined {
  if (!modelMediaSlots.has(slot)) return undefined;
  if (v4ModelSlugs.has(slug)) return "lulu-v4";
  return (
    (slot === "MODEL_FRONT" && v3ModelFrontSlugs.has(slug))
    || (slot !== "MODEL_FRONT" && v3SupplementalModelSlugs.has(slug))
  ) ? "lulu-v3" : "lulu-v2";
}

export function getWardrobePublicModelAnchor(slug: string): WardrobePublicModelAnchor {
  if (v4ModelSlugs.has(slug)) {
    return { ...WARDROBE_PUBLIC_MODEL_ANCHORS["lulu-v4"] };
  }
  return v3ModelFrontSlugs.has(slug) || v3SupplementalModelSlugs.has(slug)
    ? { ...WARDROBE_PUBLIC_MODEL_ANCHORS["lulu-v3"] }
    : { ...WARDROBE_PUBLIC_MODEL_ANCHORS["lulu-v2"] };
}

function migrationFrame(
  slug: string,
  slot: WardrobePublicMediaSlot,
  fileName: string,
): WardrobePublicMedia {
  const modelAnchorId = getApprovedModelAnchorId(slug, slot);
  return {
    slot,
    src: `/shop/products/${slug}/${fileName}`,
    ...(modelAnchorId ? { modelAnchorId } : {}),
  };
}

function migrationMedia(slug: string): WardrobePublicMedia[] {
  return [
    migrationFrame(slug, "GARMENT_FRONT", "01-garment-front.webp"),
    migrationFrame(slug, "GARMENT_BACK", "02-garment-back.webp"),
    migrationFrame(slug, "MANNEQUIN_FRONT", "03-mannequin-front.webp"),
    ...(modelFrontSlugs.has(slug)
      ? [migrationFrame(slug, "MODEL_FRONT", "04-model-front.webp")]
      : []),
    constructionDetailSlugs.has(slug)
      ? migrationFrame(slug, "CONSTRUCTION_DETAIL", "08-construction-detail.webp")
      : migrationFrame(slug, "FABRIC_DETAIL", "06-fabric-detail.webp"),
    ...getApprovedModelSupplementalSlots(slug).map((slot) => ({
      ...migrationFrame(slug, slot, supplementalModelFiles[slot]),
    })),
  ];
}

function migrationSeed(
  product: Omit<WardrobePublicProduct, "media" | "modelAnchor">,
): WardrobePublicProduct {
  return {
    ...product,
    modelAnchor: getWardrobePublicModelAnchor(product.slug),
    media: migrationMedia(product.slug),
  };
}

/**
 * One-time public migration rows for the original six-product Shop release.
 * Studio materializes matching wardrobe records and thereafter owns lifecycle.
 */
export const WARDROBE_PUBLIC_VIEW_MIGRATION_SEEDS: readonly WardrobePublicProduct[] = Object.freeze([
  migrationSeed({
    slug: "coral-drift-dress",
    sku: "JUW-001",
    name: "Coral Drift Dress",
    category: "Dresses",
    price: 24500,
    taggedSize: "UK 10",
    fit: "Relaxed 8–10",
    condition: "Excellent pre-loved",
    colour: "Washed coral",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "coral",
    silhouette: "dress",
    note: "A softly gathered midi that moves without feeling precious.",
    story: "Chosen for the easy drape and warm, sun-faded colour. The waist sits gently rather than tightly, with enough movement for everyday plans and evening light.",
    details: ["Soft woven hand", "Side zip", "Midi length", "Unlined"],
    measurements: [
      { label: "Bust", value: "88 cm" },
      { label: "Waist", value: "74 cm" },
      { label: "Length", value: "121 cm" },
    ],
  }),
  migrationSeed({
    slug: "indigo-workshirt",
    sku: "JUW-002",
    name: "Indigo Workshirt",
    category: "Shirts",
    price: 18000,
    taggedSize: "L",
    fit: "Oversized 10–14",
    condition: "Very good",
    colour: "Washed indigo",
    availability: "RESERVED",
    drop: "Drop 01",
    tone: "indigo",
    silhouette: "shirt",
    note: "Soft denim structure with the ease of a light jacket.",
    story: "A useful in-between layer with softened seams and a lived-in wash. Wear it open over a tank or buttoned with sleeves rolled once.",
    details: ["Two patch pockets", "Tonal buttons", "Soft denim", "Curved hem"],
    measurements: [
      { label: "Chest", value: "116 cm" },
      { label: "Shoulder", value: "48 cm" },
      { label: "Length", value: "73 cm" },
    ],
  }),
  migrationSeed({
    slug: "moss-square-knit",
    sku: "JUW-003",
    name: "Moss Square Knit",
    category: "Knitwear",
    price: 12500,
    taggedSize: "M",
    fit: "Fitted 8–12",
    condition: "Good — light wear",
    colour: "Moss green",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "moss",
    silhouette: "knit",
    note: "Fine rib, square neck, and a close fit that layers cleanly.",
    story: "The quiet colour does the work here. A clean neckline and fine rib make it useful under tailoring, while the stretch keeps it easy on its own.",
    details: ["Stretch rib", "Square neckline", "Long sleeve", "Close fit"],
    measurements: [
      { label: "Bust", value: "76–92 cm" },
      { label: "Sleeve", value: "59 cm" },
      { label: "Length", value: "55 cm" },
    ],
  }),
  migrationSeed({
    slug: "ivory-tie-skirt",
    sku: "JUW-004",
    name: "Ivory Tie Skirt",
    category: "Skirts",
    price: 15500,
    taggedSize: "UK 10",
    fit: "Adjustable 8–12",
    condition: "Excellent pre-loved",
    colour: "Warm ivory",
    availability: "SOLD",
    drop: "Archive",
    tone: "ivory",
    silhouette: "skirt",
    note: "An asymmetric wrap with a clean waist tie and soft movement.",
    story: "A simple wrap shape with a little asymmetry. This one has found a home, but remains in the edit as a reference for the pieces we look for.",
    details: ["Adjustable tie", "Asymmetric front", "Midi length", "Fully lined"],
    measurements: [
      { label: "Waist", value: "68–82 cm" },
      { label: "Hip", value: "104 cm" },
      { label: "Length", value: "79 cm" },
    ],
  }),
  migrationSeed({
    slug: "cocoa-pleat-trouser",
    sku: "JUW-005",
    name: "Cocoa Pleat Trouser",
    category: "Trousers",
    price: 22000,
    taggedSize: "UK 12",
    fit: "True 10–12",
    condition: "Excellent pre-loved",
    colour: "Deep cocoa",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "cocoa",
    silhouette: "trouser",
    note: "A long, fluid line with a single front pleat and gentle taper.",
    story: "The fabric falls with weight but stays breathable. A high waist and subtle taper make this pair equally good with a compact knit or oversized shirt.",
    details: ["High waist", "Single front pleat", "Side pockets", "Gentle taper"],
    measurements: [
      { label: "Waist", value: "78 cm" },
      { label: "Rise", value: "31 cm" },
      { label: "Inseam", value: "78 cm" },
    ],
  }),
  migrationSeed({
    slug: "salmon-camp-shirt",
    sku: "JUW-006",
    name: "Salmon Camp Shirt",
    category: "Shirts",
    price: 16500,
    taggedSize: "M",
    fit: "Relaxed 8–12",
    condition: "Very good",
    colour: "Soft salmon",
    availability: "AVAILABLE",
    drop: "Drop 01",
    tone: "salmon",
    silhouette: "shirt",
    note: "Airy, boxy, and cut with an open collar for warm days.",
    story: "An unfussy shirt in the exact shade that makes denim and cocoa neutrals feel considered. The boxy cut is intended to sit away from the body.",
    details: ["Open collar", "Short sleeve", "Boxy cut", "Side vents"],
    measurements: [
      { label: "Chest", value: "108 cm" },
      { label: "Shoulder", value: "44 cm" },
      { label: "Length", value: "64 cm" },
    ],
  }),
  ...WARDROBE_DROP_01_PRODUCTS.map((product) => migrationSeed({
    ...product,
    details: [...product.details],
    measurements: product.measurements.map((
      measurement: WardrobePublicProduct["measurements"][number],
    ) => ({ ...measurement })),
  })),
  migrationSeed({
    slug: "black-cropped-tee-slim-trouser-set",
    sku: "JUW-025",
    name: "Black Cropped Tee and Slim Trouser Set",
    category: "Sets",
    price: 24500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "cocoa",
    silhouette: "set",
    note: "A black cropped tee and slim trouser pairing with a clean, close line.",
    story: "Soft gathered sleeve caps meet a fitted crop, balanced by high-waisted tapered trousers with a simple silver-tone button.",
    details: ["Cropped crew-neck tee", "Soft gathered sleeve caps", "High-waisted slim trousers", "Tapered ankle length"],
    measurements: [],
  }),
  migrationSeed({
    slug: "violet-beaded-ruffle-romper",
    sku: "JUW-026",
    name: "Violet Beaded Ruffle Romper",
    category: "Rompers",
    price: 32000,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Deep violet",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "indigo",
    silhouette: "romper",
    note: "A deep-violet beaded romper framed by soft flounces and an asymmetric ruffled hem.",
    story: "Slim straps and an off-shoulder flounce open the neckline, while dense tonal beadwork carries through the close romper silhouette.",
    details: ["Slim shoulder straps", "Off-shoulder flounce", "Dense tonal beadwork", "Asymmetric ruffled hem"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-sweetheart-fit-flare-midi-dress",
    sku: "JUW-027",
    name: "Black Sweetheart Fit-and-Flare Midi Dress",
    category: "Dresses",
    price: 28500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "cocoa",
    silhouette: "dress",
    note: "A black sweetheart midi shaped through the bodice and released into a full gathered skirt.",
    story: "Curved cup seams, short structured sleeves, and a panelled waist give way to a softly gathered A-line midi skirt.",
    details: ["Sweetheart cup seams", "Short structured sleeves", "Panelled fitted bodice", "Gathered A-line midi skirt"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-ivory-folded-neck-column-dress",
    sku: "JUW-028",
    name: "Black and Ivory Folded-Neck Column Dress",
    category: "Dresses",
    price: 34500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black and ivory",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "ivory",
    silhouette: "dress",
    note: "A floor-length black column set off by a broad folded ivory neckline.",
    story: "The wide off-shoulder fold frames a low open neckline before the dress falls into a long, close column silhouette.",
    details: ["Broad folded ivory neckline", "Off-shoulder line", "Close column silhouette", "Floor length"],
    measurements: [],
  }),
  migrationSeed({
    slug: "indigo-seamed-denim-mini-dress",
    sku: "JUW-029",
    name: "Indigo Seamed Denim Mini Dress",
    category: "Dresses",
    price: 28500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Medium-deep indigo",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "indigo",
    silhouette: "dress",
    note: "A close indigo denim mini shaped by long seams and a softly rounded hem.",
    story: "A clean jewel neckline and plain long sleeves frame the fitted line, with restrained topstitching carrying through the compact silhouette.",
    details: ["Shallow jewel neckline", "Long plain sleeves", "Closed centre construction line", "Fitted mini length"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-cropped-tee-silver-ruched-skirt-set",
    sku: "JUW-030",
    name: "Black Cropped Tee and Silver Ruched Skirt Set",
    category: "Sets",
    price: 28500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black and silver",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "ivory",
    silhouette: "set",
    note: "A matte-black cropped tee paired with a close silver ruched skirt and one high front slit.",
    story: "The clean crew-neck crop keeps the top quiet while the reflective ruching and high centre-front slit give the skirt its movement.",
    details: ["Cropped crew-neck tee", "High-waisted pencil skirt", "Reflective ruched finish", "Single high centre-front slit"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-cropped-tee-pink-distressed-shorts-set",
    sku: "JUW-031",
    name: "Black Cropped Tee and Pink Distressed Shorts Set",
    category: "Sets",
    price: 19500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black and pink",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "coral",
    silhouette: "set",
    note: "A matte-black cropped tee paired with vivid pink distressed cut-off denim shorts.",
    story: "The close crew-neck crop leaves a clean waist gap above high-rise washed-pink denim shorts, finished with front distress and uneven raw frayed hems.",
    details: ["Cropped crew-neck tee", "High-rise denim shorts", "Front pocket and fly construction", "Distressed raw frayed hems"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-cropped-tee-blue-distressed-shorts-set",
    sku: "JUW-032",
    name: "Black Cropped Tee and Blue Distressed Shorts Set",
    category: "Sets",
    price: 19500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black and medium blue",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "indigo",
    silhouette: "set",
    note: "A matte-black cropped tee paired with washed blue distressed cut-off denim shorts.",
    story: "The close crew-neck crop leaves a clean waist gap above high-rise medium-blue denim shorts, finished with asymmetric front distress, relaxed openings and uneven raw frayed hems.",
    details: ["Cropped crew-neck tee", "High-rise denim shorts", "Asymmetric front distress", "Short raw frayed hems"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-cropped-tee-charcoal-cutoff-shorts-set",
    sku: "JUW-033",
    name: "Black Cropped Tee and Charcoal Cut-Off Shorts Set",
    category: "Sets",
    price: 19500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black and washed charcoal",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "cocoa",
    silhouette: "set",
    note: "A matte-black cropped tee paired with washed charcoal-black cut-off denim shorts.",
    story: "The close crew-neck crop leaves a clean waist gap above high-rise washed charcoal denim shorts, finished with a clean front, relaxed openings and very short irregular raw-frayed hems.",
    details: ["Cropped crew-neck tee", "High-rise denim shorts", "Clean minimally distressed front", "Very short irregular raw-frayed hems"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-cropped-tee-mid-thigh-black-cutoff-shorts-set",
    sku: "JUW-034",
    name: "Black Cropped Tee and Mid-Thigh Black Cut-Off Shorts Set",
    category: "Sets",
    price: 19500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "cocoa",
    silhouette: "set",
    note: "A matte-black cropped tee paired with clean deep-black mid-thigh cut-off shorts.",
    story: "The fitted crew-neck crop leaves a small waist gap above high-rise clean black shorts, shaped close through the hips before opening into longer straight legs with restrained raw fringe.",
    details: ["Cropped crew-neck tee", "High-rise black denim shorts", "Longer mid-thigh cut", "Short fine raw fringe"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-cropped-tee-light-wash-snap-panel-trousers-set",
    sku: "JUW-035",
    name: "Black Cropped Tee and Light-Wash Snap-Panel Trousers Set",
    category: "Sets",
    price: 24500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black, light-wash blue and dark indigo",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "indigo",
    silhouette: "set",
    note: "A matte-black cropped tee paired with light-wash wide-leg trousers and dark snap-detailed outer panels.",
    story: "The fitted black crop sits above a gathered pull-on waist and long white drawcords, while broad light-wash legs fall to the floor beside dark indigo outer panels punctuated by silver-tone snaps.",
    details: ["Cropped crew-neck tee", "Gathered pull-on waistband and drawcord", "Wide full-length legs", "Dark outer panels with silver-tone snaps"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-cropped-tee-blue-wash-drawstring-barrel-trousers-set",
    sku: "JUW-036",
    name: "Black Cropped Tee and Blue-Wash Drawstring Barrel Trousers Set",
    category: "Sets",
    price: 24500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black and medium-wash blue",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "indigo",
    silhouette: "set",
    note: "A matte-black cropped tee paired with medium-wash pull-on denim barrel trousers.",
    story: "The fitted crop leaves a clean waist gap above a broad gathered waistband and white drawstring, while relaxed washed-blue legs taper softly toward the ankles.",
    details: ["Cropped crew-neck tee", "Gathered pull-on waistband and white drawstring", "Angled hip pockets", "Relaxed barrel legs with tapered ankle openings"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-cropped-tee-charcoal-wash-wide-leg-cargo-jeans-set",
    sku: "JUW-037",
    name: "Black Cropped Tee and Charcoal-Wash Wide-Leg Cargo Jeans Set",
    category: "Sets",
    price: 24500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black and washed charcoal-grey",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "cocoa",
    silhouette: "set",
    note: "A matte-black cropped tee paired with washed charcoal-grey wide-leg cargo jeans.",
    story: "The fitted crop leaves a clean waist gap above fixed-waist charcoal-wash jeans, with compact outer-thigh utility pockets and wide straight legs falling to full length.",
    details: ["Cropped crew-neck tee", "Fixed waistband with button and fly", "Compact outer-thigh utility pockets", "Wide straight full-length legs"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-cropped-tee-dark-indigo-wide-leg-cargo-jeans-set",
    sku: "JUW-038",
    name: "Black Cropped Tee and Dark Indigo Wide-Leg Cargo Jeans Set",
    category: "Sets",
    price: 24500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black and dark indigo",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "indigo",
    silhouette: "set",
    note: "A matte-black cropped tee paired with dark-indigo washed wide-leg cargo jeans.",
    story: "The fitted crop leaves a clean waist gap above fixed-waist dark-indigo jeans, with compact outer-thigh utility pockets and broad straight legs falling to full length.",
    details: ["Cropped crew-neck tee", "Fixed waistband with button and fly", "Compact outer-thigh utility pockets", "Broad straight full-length legs"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-cropped-tee-washed-black-wide-leg-cargo-jeans-set",
    sku: "JUW-039",
    name: "Black Cropped Tee and Washed Black Wide-Leg Cargo Jeans Set",
    category: "Sets",
    price: 24500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Black and washed black",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "cocoa",
    silhouette: "set",
    note: "A matte-black cropped tee paired with washed-black wide-leg cargo jeans.",
    story: "The fitted crop leaves a clean waist gap above fixed-waist washed-black jeans, finished with a centred button and fly, curved front pockets, compact outer-thigh cargo pockets and broad full-length legs.",
    details: ["Cropped crew-neck tee", "Fixed waistband with button and fly", "Curved hip-pocket openings and compact outer-thigh cargo pockets", "Broad washed-black full-length legs"],
    measurements: [],
  }),
  migrationSeed({
    slug: "plum-sparkle-cowl-neck-jumpsuit",
    sku: "JUW-040",
    name: "Plum Sparkle Cowl-Neck Jumpsuit",
    category: "Rompers",
    price: 28500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Deep plum",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "indigo",
    silhouette: "romper",
    note: "A deep-plum sparkle jumpsuit with a softly draped cowl neckline and a long, close-to-straight line.",
    story: "A softly folded cowl frames the neckline above an uninterrupted fitted body, opening into full-length straight legs with fine tonal sparkle throughout.",
    details: ["Soft draped cowl neckline", "Extended cap shoulders", "Fitted one-piece silhouette", "Full-length straight legs"],
    measurements: [],
  }),
  migrationSeed({
    slug: "gunmetal-sparkle-open-back-long-sleeve-mini-dress",
    sku: "JUW-041",
    name: "Gunmetal Sparkle Open-Back Long-Sleeve Mini Dress",
    category: "Dresses",
    price: 28500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Gunmetal charcoal",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "cocoa",
    silhouette: "dress",
    note: "A fitted gunmetal sparkle mini with a plunging crossover front and sculptural open-back straps.",
    story: "A deep crossover neckline meets a raised waist and close mini silhouette, while the back opens into two cutouts divided by a narrow connector strap.",
    details: ["Deep crossover V neckline", "Long close sleeves", "Raised waist band", "Two-part open-back construction"],
    measurements: [],
  }),
  migrationSeed({
    slug: "fuchsia-strapless-ruched-cascade-ruffle-mini-dress",
    sku: "JUW-042",
    name: "Fuchsia Strapless Ruched Cascade-Ruffle Mini Dress",
    category: "Dresses",
    price: 28500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Saturated fuchsia",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "coral",
    silhouette: "dress",
    note: "A saturated fuchsia strapless mini shaped with dense ruching and one cascading asymmetric ruffle.",
    story: "A softly dipped strapless neckline meets a close ruched body, while one layered front cascade continues below the mini hem as a fluid free tail.",
    details: ["Softly dipped strapless neckline", "Dense horizontal ruching", "Asymmetric layered front ruffle", "Extended free ruffle tail"],
    measurements: [],
  }),
  migrationSeed({
    slug: "charcoal-wrap-front-ruched-slit-midi-dress",
    sku: "JUW-043",
    name: "Charcoal Wrap-Front Ruched Slit Midi Dress",
    category: "Dresses",
    price: 28500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Charcoal black",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "cocoa",
    silhouette: "dress",
    note: "A charcoal-black fitted midi shaped by a deep crossover front and asymmetric ruching.",
    story: "Long close sleeves frame a deep wrap-front V, with diagonal folds drawing through the waist into a fitted midi skirt and one narrow front slit.",
    details: ["Deep crossover V neckline", "Long fitted sleeves", "Asymmetric diagonal ruching", "Narrow front slit"],
    measurements: [],
  }),
  migrationSeed({
    slug: "marigold-sculptural-rosette-strapless-mini-dress",
    sku: "JUW-044",
    name: "Marigold Sculptural Rosette Strapless Mini Dress",
    category: "Dresses",
    price: 32500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Marigold yellow",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "coral",
    silhouette: "dress",
    note: "A bright marigold strapless mini framed by two dimensional pleated rosettes.",
    story: "A clean bandeau neckline opens into sculptural pleated flowers across the front, balanced by a softly gathered mini skirt and layered ruffle hem.",
    details: ["Straight strapless neckline", "Two sculptural pleated rosettes", "Diagonal folded-petal front", "Layered ruffle mini hem"],
    measurements: [],
  }),
  migrationSeed({
    slug: "scarlet-rosette-halter-cutout-ruched-mini-dress",
    sku: "JUW-045",
    name: "Scarlet Rosette Halter Cutout Ruched Mini Dress",
    category: "Dresses",
    price: 27500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Scarlet red",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "coral",
    silhouette: "dress",
    note: "A scarlet halter mini shaped by a dimensional centre rosette, an open midriff and dense ruching.",
    story: "A gathered halter bandeau lifts around one sculptural fabric rose, opening into a defined midriff cutout above a close high-waisted ruched mini.",
    details: ["Narrow halter straps", "Dimensional centre rosette", "Open midriff cutout", "High-waisted ruched mini"],
    measurements: [],
  }),
  migrationSeed({
    slug: "crimson-asymmetric-draped-satin-maxi-dress",
    sku: "JUW-046",
    name: "Crimson Asymmetric Draped Satin Maxi Dress",
    category: "Dresses",
    price: 34500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Deep crimson",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "coral",
    silhouette: "dress",
    note: "A deep-crimson satin maxi defined by one sculptural shoulder and a softly gathered waist.",
    story: "A wide asymmetric shoulder rises above a fluid draped neckline, with gathered folds shaping the bodice before the satin falls into a long straight column.",
    details: ["Asymmetric one-shoulder neckline", "Softly draped satin-like bodice", "Gathered low waist", "Straight floor-length column"],
    measurements: [],
  }),
  migrationSeed({
    slug: "scarlet-asymmetric-cascade-ruched-mini-dress",
    sku: "JUW-047",
    name: "Scarlet Asymmetric Cascade Ruched Mini Dress",
    category: "Dresses",
    price: 29500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Scarlet red",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "coral",
    silhouette: "dress",
    note: "A scarlet long-sleeve mini shaped by an asymmetric neckline, dense ruching and one fluid hip cascade.",
    story: "A wide gathered neckline rises toward one shoulder above diagonal bodice drape, while close skirt ruching resolves into a rosette knot and an extended asymmetric ruffle.",
    details: ["Asymmetric gathered neckline", "Long fitted sleeves", "Dense ruched mini silhouette", "Rosette hip knot with extended cascade"],
    measurements: [],
  }),
  migrationSeed({
    slug: "black-asymmetric-sculpted-shoulder-mini-dress",
    sku: "JUW-048",
    name: "Black Asymmetric Sculpted-Shoulder Mini Dress",
    category: "Dresses",
    price: 27500,
    taggedSize: "Size on request",
    fit: "Measurements confirmed before payment",
    condition: "Condition confirmed before payment",
    colour: "Deep black",
    availability: "AVAILABLE",
    drop: "Drop 02",
    tone: "coral",
    silhouette: "dress",
    note: "A deep-black long-sleeve mini shaped by a sculpted asymmetric neckline and layered shoulder flounce.",
    story: "A sweeping neckline exposes one shoulder while a layered flounce frames the other, above a smooth close-fitting mini silhouette.",
    details: ["Sculpted asymmetric neckline", "Layered right-shoulder flounce", "Two fitted long sleeves", "Smooth bodycon mini silhouette"],
    measurements: [],
  }),
]);

export function createWardrobePublicViewMigrationSnapshot(): WardrobePublicViewSnapshot {
  return {
    products: WARDROBE_PUBLIC_VIEW_MIGRATION_SEEDS.map((product) => ({
      ...product,
      details: [...product.details],
      measurements: product.measurements.map((measurement) => ({ ...measurement })),
      modelAnchor: { ...product.modelAnchor },
      media: product.media.map((item) => ({ ...item })),
    })),
    managedSlugs: WARDROBE_PUBLIC_VIEW_MIGRATION_SEEDS.map((product) => product.slug),
  };
}
